theme: jekyll-theme-modernist
logo: M
# add logo name
title: Freedom - May
description: > # this means to ignore newlines until "baseurl:"
  程序员/太极修炼者/化妆师/作家的跨界成长社区，探讨技术赋能、文化传承与副业变现，
  提供技术博客运营、非遗数字化、开发者形象管理等实战指南
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog  /bef
url: "https://May16138cccccccccccccccc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

## Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "代码之外的可能性" # add banner title
banner-desc: # add banner description
#
## Author settings
author-pic: face.jpg # your photo
author-name: "CM | 全栈开发者"
# your name
about-author: 这里是程序员打破次元壁的成长社区，专为「用代码改变世界，用热爱重塑生活」的斜杠开发者打造。
# about author
email: 2951400450@qq.com # your email
phone: (496)-169-6557 # your pnone number
website: https://blog.csdn.net/weixin_53538280?type=blog # you website
#
## Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link
#
## Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/
# #
# ## Newsletter
# mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
# #
# ## Tracker
# analytics:

# # Paginate
# paginate: 12
# paginate_path: /page:num/

# # Build settings
# markdown: kramdown
# plugins_dir:
#  - jekyll-paginate
#  - jekyll-sitemap

gems:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-theme-modernist
# include: [_pages]
# exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

